apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: golang-echo-sample:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        resources: {}
        ports:
        - containerPort: 8080
