apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: mysql
data:
  initdb.sql: |
    CREATE TABLE users (id INT, name VARCHAR(256));
    INSERT INTO users VALUES (1, 'Ryota');
    INSERT INTO users VALUES (2, 'Kenji');
    INSERT INTO users VALUES (3, 'Taro');

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf-config
  namespace: mysql
data:
  custom.cnf: |
    [mysqld]
    character-set-server=utf8